# Managed by Puppet
#
# .bashrc
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
# User specific aliases and functions

# Adding /usr/local to path
export PATH=$PATH:/usr/local/bin 

cowsay 'Skeletons are awesome!'
